# A docker-compose must always start by the version tag.
version: "3.9"

# Define services
services:

  subscriber1:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 1 --BID 16 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.1

  subscriber2:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 2 --BID 16 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.2

  subscriber3:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 3 --BID 16 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.3

  subscriber4:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 4 --BID 17 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.4

  subscriber5:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 5 --BID 17 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.5

  subscriber6:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 6 --BID 17 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.6

  subscriber7:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 7 --BID 18 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.7

  subscriber8:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 8 --BID 18 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.8

  subscriber9:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 9 --BID 18 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.9

  subscriber10:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 10 --BID 19 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.10

  subscriber11:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 11 --BID 19 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.11

  subscriber12:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 12 --BID 19 --mode subscriber
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.12

  publisher13:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 13 --BID 20 --mode publisher
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.13

  publisher14:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type client --ID 14 --BID 15 --mode publisher
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.14

  edgebroker15:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 15 --NB 20
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.15

  edgebroker16:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 16 --NB 23
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.16

  edgebroker17:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 17 --NB 24
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.17

  edgebroker18:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 18 --NB 23
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.18

  edgebroker19:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 19 --NB 21
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.19

  edgebroker20:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 20 --NB 21,15
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.20

  broker21:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 21 --NB 20,19,22
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.21

  broker22:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 22 --NB 21,23
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.22

  broker23:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 23 --NB 22,16,18,24
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.23

  broker24:
    # Path of Dockerfile
    build: .
    # The command to execute once the image is created.
    command: java -jar ./target/DS-Project-V1.0.0-jar-with-dependencies.jar --type broker --ID 24 --NB 23,17
    volumes:
      - ${DIRECTORY_SAVE}:/tmp
    networks:
      broker_network:
        ipv4_address: 192.168.2.24

# Set up custom network
networks:
  broker_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.1.1